#!/bin/sh

# Define the regex pattern to match the commit message against
pattern="^\[(FEATURE|BUGFIX|CHORE|HOTFIX)\] .{1,50}$"

# Read the commit message from stdin
commit_msg=$(cat "$1")

# Check if the commit message matches the required pattern
if ! echo "$commit_msg" | grep -iqE "$pattern"; then
    echo "Commit message should start with either [FEATURE] or [BUGFIX] etc ..."
    echo "Followed by a space and then a brief description of the change (50 characters or less)."
    exit 1
fi
